"""Initial migration

Revision ID: 1cb935d9c957
Revises: 
Create Date: 2025-04-21 00:01:27.940365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb935d9c957'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'glucose_readings',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('timestamp', sa.Integer(), unique=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glucose_readings')
    # ### end Alembic commands ###
