"""adding api_user

Revision ID: 61f48ac5e69a
Revises: 1cb935d9c957
Create Date: 2025-08-25 21:01:30.097661

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61f48ac5e69a'
down_revision: Union[str, None] = '1cb935d9c957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_api_users_id'), 'api_users', ['id'], unique=False)
    op.create_index(op.f('ix_glucose_readings_id'), 'glucose_readings', ['id'], unique=False)
    op.create_index(op.f('ix_glucose_readings_timestamp'), 'glucose_readings', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glucose_readings_timestamp'), table_name='glucose_readings')
    op.drop_index(op.f('ix_glucose_readings_id'), table_name='glucose_readings')
    op.drop_index(op.f('ix_api_users_id'), table_name='api_users')
    op.drop_table('api_users')
    # ### end Alembic commands ###
